### ISSUE TITLE
Trouble changing HAC plot Width.  Plot Height/Width option missing from PCA.

### ISSUE THREAD

**Issue by tsamop** [dgrapov/DeviumWeb#6]
FANTASTIC APPLICATION, THANK YOU!

I'm trying to work with a 242x45 sample data set, so I want to increase the plot size to read the annotations of the individual points.

1). On the Hierarchical Clustering plot, I was unable to adjust the plot width by changing the value in Plot>More Options>Width.  Changing the value did not seem to have an effect on plot width.

2). Changing the plot Height in the Hierarchical Clustering plot changed the plot height in the Principal component analysis plot as well.

3). I could not find any place to change the size of the plot in the Principal Component Analysis plot.

![screen shot 2015-09-11 at 3 44 04 pm](https://cloud.githubusercontent.com/assets/5874658/9828428/11e95672-58a2-11e5-8609-923333e015fa.png)

![screen shot 2015-09-11 at 4 07 48 pm](https://cloud.githubusercontent.com/assets/5874658/9828250/ade24618-589f-11e5-8f73-0d5bc0105dba.png)

**Comment by dgrapov** [comment]
I'll take a look at this.

**Comment by rabiecqa** [comment]
Hi, the issue was from 
![devium_2](https://cloud.githubusercontent.com/assets/14331738/9962682/4ad78b36-5e27-11e5-8fbe-08c6768a3338.png)
 shiny.
with  Shiny (v0.10.2.2) it's work fine !
Hope that you will made some modifications to adapt it to the last version of shiny.
any way thanks  :-),
